import SwiftUI
import PDFKit

// MARK: - Report Detail View
struct ReportDetailView: View {
    let reportType: ReportType
    let content: String?
    let profile: Profile?
    let symptoms: [Symptom]
    let medications: [HistoryMedication]
    let birthControls: [BirthControl]
    let treatments: [Treatment]
    let therapies: [Therapy]
    let familyHistory: [FamilyHistory]
    let onBack: () -> Void

    @State private var pdfURL: URL?
    @State private var showShareSheet = false
    @State private var isGeneratingPDF = false

    var body: some View {
        NavigationStack {
            ZStack {
                Color.warmWhite.ignoresSafeArea()
                ScrollView {
                    VStack(alignment: .leading, spacing: 20) {
                        // Header
                        VStack(alignment: .leading, spacing: 4) {
                            Text(reportType.label)
                                .font(.custom("DMSans-SemiBold", size: 24))
                                .foregroundColor(.charcoal)
                            Text("Generated \(Date().formatted(.dateTime.day().month(.wide).year()))")
                                .font(.custom("DMSans-Regular", size: 13))
                                .foregroundColor(.slateMid)
                        }

                        // Disclaimer
                        Text("This document is a self-reported symptom log generated by EndoAlly. It does not constitute a medical assessment, diagnosis, or clinical opinion.")
                            .font(.custom("DMSans-Regular", size: 12))
                            .foregroundColor(.slateMid)
                            .padding(12)
                            .background(Color.warmWhite)
                            .cornerRadius(8)
                            .overlay(RoundedRectangle(cornerRadius: 8).stroke(Color.appBorder, lineWidth: 1))

                        // AI content
                        if let aiContent = content {
                            MarkdownTextView(markdown: aiContent)
                        }

                        // Symptom Timeline
                        if reportType.id == "timeline" || reportType.id == "full" || content == nil {
                            if !symptoms.isEmpty {
                                VStack(alignment: .leading, spacing: 12) {
                                    Text("Symptom Timeline")
                                        .font(.custom("DMSans-SemiBold", size: 18))
                                        .foregroundColor(.charcoal)
                                    Divider()
                                    ForEach(buildTimeline(), id: \.name) { item in
                                        SymptomTimelineRow(item: item)
                                    }
                                }
                            }
                        }

                        // Medications
                        if (reportType.id == "medhistory" || reportType.id == "full" || reportType.id == "specialist") && !medications.isEmpty {
                            HistorySection(title: "Regular Medications") {
                                ForEach(medications) { med in
                                    HistoryRow(
                                        title: "\(med.name)\(med.dose.map { " — \($0)" } ?? "")",
                                        meta: [med.frequency, med.forWhat, med.stillTaking ? "Currently taking" : "No longer taking"]
                                            .compactMap { $0 }.joined(separator: " · ")
                                    )
                                }
                            }
                        }

                        // Birth Control
                        if (reportType.id == "medhistory" || reportType.id == "full" || reportType.id == "specialist") && !birthControls.isEmpty {
                            HistorySection(title: "Birth Control History") {
                                ForEach(birthControls) { bc in
                                    HistoryRow(
                                        title: bc.displayDescription,
                                        meta: bc.stillUsing ? "Currently using" : "Past"
                                    )
                                }
                            }
                        }

                        // Treatments
                        if (reportType.id == "medhistory" || reportType.id == "full" || reportType.id == "specialist") && !treatments.isEmpty {
                            HistorySection(title: "Past Treatments") {
                                ForEach(treatments) { t in
                                    HistoryRow(
                                        title: t.name,
                                        meta: [t.treatmentType, t.date, t.outcome].compactMap { $0 }.joined(separator: " · ")
                                    )
                                }
                            }
                        }

                        // Therapies
                        if (reportType.id == "medhistory" || reportType.id == "full") && !therapies.isEmpty {
                            HistorySection(title: "Therapies & Exercises") {
                                ForEach(therapies) { t in
                                    HistoryRow(
                                        title: t.name,
                                        meta: [t.therapyType, t.frequency].compactMap { $0 }.joined(separator: " · ")
                                    )
                                }
                            }
                        }

                        // Family History
                        if (reportType.id == "full" || reportType.id == "specialist") && !familyHistory.isEmpty {
                            HistorySection(title: "Family History") {
                                ForEach(familyHistory) { fh in
                                    HistoryRow(title: "\(fh.relation) — \(fh.condition)", meta: fh.notes ?? "")
                                }
                            }
                        }

                        // Export PDF button
                        Button(action: exportPDF) {
                            HStack {
                                if isGeneratingPDF {
                                    ProgressView().tint(.white)
                                } else {
                                    Image(systemName: "square.and.arrow.up")
                                    Text("Export PDF")
                                        .font(.custom("DMSans-Bold", size: 15))
                                }
                            }
                            .frame(maxWidth: .infinity)
                            .padding(.vertical, 14)
                            .background(Color.rose)
                            .foregroundColor(.white)
                            .cornerRadius(10)
                        }
                        .disabled(isGeneratingPDF)
                    }
                    .padding(.horizontal, 16)
                    .padding(.vertical, 20)
                }
            }
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Back", action: onBack).foregroundColor(.rose)
                }
            }
        }
        .sheet(isPresented: $showShareSheet) {
            if let url = pdfURL {
                ShareSheet(items: [url])
            }
        }
    }

    // MARK: - Timeline builder
    struct TimelineItem {
        let name: String
        let category: String
        let count: Int
        let avgSeverity: Double?
        let phases: [String]
        let firstDate: String
    }

    private func buildTimeline() -> [TimelineItem] {
        var map = [String: (count: Int, sevs: [Int], phases: Set<String>, first: String, cat: String)]()
        let fmt = DateFormatter()
        fmt.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZ"
        let displayFmt = DateFormatter()
        displayFmt.dateFormat = "d MMM yyyy"
        displayFmt.locale = Locale(identifier: "en_AU")

        for s in symptoms {
            if map[s.symptom] == nil {
                map[s.symptom] = (0, [], Set(), s.loggedAt, s.category)
            }
            map[s.symptom]!.count += 1
            if let sev = s.severity { map[s.symptom]!.sevs.append(sev) }
            if let phase = s.phase { map[s.symptom]!.phases.insert(phase) }
            if s.loggedAt < map[s.symptom]!.first { map[s.symptom]!.first = s.loggedAt }
        }

        return map.map { (name, data) in
            let avgSev: Double? = data.sevs.isEmpty ? nil : Double(data.sevs.reduce(0, +)) / Double(data.sevs.count)
            let firstStr: String
            if let d = fmt.date(from: data.first) { firstStr = displayFmt.string(from: d) }
            else { firstStr = data.first }
            return TimelineItem(name: name, category: data.cat, count: data.count, avgSeverity: avgSev,
                                phases: Array(data.phases), firstDate: firstStr)
        }.sorted { $0.count > $1.count }
    }

    // MARK: - PDF export
    private func exportPDF() {
        isGeneratingPDF = true
        Task {
            let renderer = PDFRenderer(
                reportType: reportType,
                content: content,
                profile: profile,
                symptoms: symptoms,
                medications: medications,
                birthControls: birthControls,
                treatments: treatments,
                therapies: therapies,
                familyHistory: familyHistory
            )
            if let url = await renderer.render() {
                pdfURL = url
                showShareSheet = true
            }
            isGeneratingPDF = false
        }
    }
}

// MARK: - Markdown text view
struct MarkdownTextView: View {
    let markdown: String

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            ForEach(parseBlocks(markdown), id: \.id) { block in
                switch block.type {
                case "h2":
                    Text(block.text)
                        .font(.custom("DMSans-SemiBold", size: 16))
                        .foregroundColor(.charcoal)
                        .padding(.top, 8)
                case "h3":
                    Text(block.text)
                        .font(.custom("DMSans-SemiBold", size: 14))
                        .foregroundColor(.charcoal)
                case "bullet":
                    HStack(alignment: .top, spacing: 8) {
                        Text("•")
                            .foregroundColor(.rose)
                        Text(block.text)
                            .font(.custom("DMSans-Regular", size: 14))
                            .foregroundColor(.charcoal)
                    }
                default:
                    if !block.text.hasPrefix("#") {
                        Text(block.text)
                            .font(.custom("DMSans-Regular", size: 14))
                            .foregroundColor(.charcoal)
                    }
                }
            }
        }
    }

    struct Block: Identifiable {
        let id = UUID()
        let type: String
        let text: String
    }

    private func parseBlocks(_ content: String) -> [Block] {
        content.components(separatedBy: "\n").compactMap { raw in
            let line = raw.trimmingCharacters(in: .whitespaces)
            if line.isEmpty { return nil }
            if line.hasPrefix("## ")  { return Block(type: "h2",   text: String(line.dropFirst(3))) }
            if line.hasPrefix("### ") { return Block(type: "h3",   text: String(line.dropFirst(4))) }
            if line.hasPrefix("- ") || line.hasPrefix("* ") { return Block(type: "bullet", text: String(line.dropFirst(2))) }
            return Block(type: "paragraph", text: line)
        }
    }
}

// MARK: - History Section
struct HistorySection<Content: View>: View {
    let title: String
    @ViewBuilder let content: () -> Content

    var body: some View {
        VStack(alignment: .leading, spacing: 10) {
            Text(title)
                .font(.custom("DMSans-SemiBold", size: 18))
                .foregroundColor(.charcoal)
            Divider()
            content()
        }
    }
}

// MARK: - History Row
struct HistoryRow: View {
    let title: String
    let meta: String

    var body: some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(title)
                .font(.custom("DMSans-SemiBold", size: 14))
                .foregroundColor(.charcoal)
            if !meta.isEmpty {
                Text(meta)
                    .font(.custom("DMSans-Regular", size: 12))
                    .foregroundColor(.slateMid)
            }
        }
        .padding(.vertical, 6)
        .overlay(Divider(), alignment: .bottom)
    }
}

// MARK: - Symptom Timeline Row
struct SymptomTimelineRow: View {
    let item: ReportDetailView.TimelineItem

    var body: some View {
        HStack(alignment: .top) {
            VStack(alignment: .leading, spacing: 2) {
                Text(item.name)
                    .font(.custom("DMSans-SemiBold", size: 13))
                    .foregroundColor(.charcoal)
                Text(item.category)
                    .font(.custom("DMSans-Regular", size: 11))
                    .foregroundColor(.slateMid)
            }
            Spacer()
            VStack(alignment: .trailing, spacing: 2) {
                Text("×\(item.count)")
                    .font(.custom("DMSans-Bold", size: 13))
                    .foregroundColor(.rose)
                if let avg = item.avgSeverity {
                    Text(String(format: "%.1f/10", avg))
                        .font(.custom("DMSans-Regular", size: 11))
                        .foregroundColor(.slateMid)
                }
                Text(item.firstDate)
                    .font(.custom("DMSans-Regular", size: 11))
                    .foregroundColor(.slateMid)
            }
        }
        .padding(.vertical, 8)
        .overlay(Divider(), alignment: .bottom)
    }
}

// MARK: - Share Sheet
struct ShareSheet: UIViewControllerRepresentable {
    let items: [Any]
    func makeUIViewController(context: Context) -> UIActivityViewController {
        UIActivityViewController(activityItems: items, applicationActivities: nil)
    }
    func updateUIViewController(_ vc: UIActivityViewController, context: Context) {}
}

// MARK: - PDF Renderer (PDFKit)
class PDFRenderer {
    let reportType: ReportType
    let content: String?
    let profile: Profile?
    let symptoms: [Symptom]
    let medications: [HistoryMedication]
    let birthControls: [BirthControl]
    let treatments: [Treatment]
    let therapies: [Therapy]
    let familyHistory: [FamilyHistory]

    init(reportType: ReportType, content: String?, profile: Profile?,
         symptoms: [Symptom], medications: [HistoryMedication], birthControls: [BirthControl],
         treatments: [Treatment], therapies: [Therapy], familyHistory: [FamilyHistory]) {
        self.reportType    = reportType
        self.content       = content
        self.profile       = profile
        self.symptoms      = symptoms
        self.medications   = medications
        self.birthControls = birthControls
        self.treatments    = treatments
        self.therapies     = therapies
        self.familyHistory = familyHistory
    }

    func render() async -> URL? {
        let pageRect = CGRect(x: 0, y: 0, width: 595, height: 842) // A4 points
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)

        let data = renderer.pdfData { ctx in
            ctx.beginPage()
            drawPage(ctx: ctx, pageRect: pageRect)
        }

        let tmpURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("\(reportType.label.replacingOccurrences(of: " ", with: "_"))_\(Date().formatted(.dateTime.year().month().day())).pdf")
        try? data.write(to: tmpURL)
        return tmpURL
    }

    private func drawPage(ctx: UIGraphicsPDFRendererContext, pageRect: CGRect) {
        let margin: CGFloat = 50
        var y: CGFloat = margin
        let maxW = pageRect.width - margin * 2

        // Rose color
        let roseColor = UIColor(red: 0.659, green: 0.212, blue: 0.345, alpha: 1)
        let charcoalColor = UIColor(red: 0.102, green: 0.153, blue: 0.22, alpha: 1)
        let slateColor = UIColor(red: 0.333, green: 0.376, blue: 0.439, alpha: 1)

        // Header logo
        let logoAttr: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 22, weight: .regular),
            .foregroundColor: charcoalColor
        ]
        let logoAllyAttr: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 22, weight: .bold),
            .foregroundColor: roseColor
        ]
        let endoStr = NSAttributedString(string: "Endo", attributes: logoAttr)
        let allyStr = NSAttributedString(string: "Ally", attributes: logoAllyAttr)
        let combined = NSMutableAttributedString()
        combined.append(endoStr)
        combined.append(allyStr)
        combined.draw(at: CGPoint(x: margin, y: y))

        // Date top right
        let dateStr = Date().formatted(.dateTime.day().month(.wide).year())
        let dateAttr: [NSAttributedString.Key: Any] = [.font: UIFont.systemFont(ofSize: 9), .foregroundColor: slateColor]
        let dateNS = NSAttributedString(string: "Generated \(dateStr)", attributes: dateAttr)
        let dateSize = dateNS.size()
        dateNS.draw(at: CGPoint(x: pageRect.width - margin - dateSize.width, y: y + 6))

        y += 32

        // Rose divider
        roseColor.setFill()
        UIBezierPath(rect: CGRect(x: margin, y: y, width: maxW, height: 1.5)).fill()
        y += 10

        // Disclaimer
        let disclaimerAttr: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 8),
            .foregroundColor: slateColor
        ]
        let disclaimer = "This document is a self-reported symptom log generated by EndoAlly. It does not constitute a medical assessment, diagnosis, or clinical opinion. It has been prepared to assist you in communicating your experiences to a qualified Australian healthcare provider."
        let disclaimerNS = NSAttributedString(string: disclaimer, attributes: disclaimerAttr)
        let disclaimerRect = CGRect(x: margin, y: y, width: maxW, height: 40)
        disclaimerNS.draw(in: disclaimerRect)
        y += 36

        // Title
        let titleAttr: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 20, weight: .bold),
            .foregroundColor: charcoalColor
        ]
        NSAttributedString(string: reportType.label, attributes: titleAttr).draw(at: CGPoint(x: margin, y: y))
        y += 28

        // Patient meta
        if let p = profile {
            let metaParts = [p.name, p.age.map { "Age \($0)" }, p.cycleLength.map { "Cycle: \($0) days" }].compactMap { $0 }
            let metaAttr: [NSAttributedString.Key: Any] = [.font: UIFont.systemFont(ofSize: 10), .foregroundColor: slateColor]
            NSAttributedString(string: metaParts.joined(separator: "  ·  "), attributes: metaAttr).draw(at: CGPoint(x: margin, y: y))
            y += 20
        }

        y += 10

        // AI content
        if let aiContent = content {
            for line in aiContent.components(separatedBy: "\n") {
                if y > pageRect.height - 80 { ctx.beginPage(); y = margin }
                let trimmed = line.trimmingCharacters(in: .whitespaces)
                if trimmed.isEmpty { y += 6; continue }

                let isH2     = trimmed.hasPrefix("## ")
                let isH3     = trimmed.hasPrefix("### ")
                let isBullet = trimmed.hasPrefix("- ") || trimmed.hasPrefix("* ")

                let text: String
                let font: UIFont
                if isH2 {
                    text = String(trimmed.dropFirst(3))
                    font = UIFont.systemFont(ofSize: 13, weight: .bold)
                    y += 8
                } else if isH3 {
                    text = String(trimmed.dropFirst(4))
                    font = UIFont.systemFont(ofSize: 11, weight: .semibold)
                } else if isBullet {
                    text = "• " + String(trimmed.dropFirst(2))
                    font = UIFont.systemFont(ofSize: 10)
                } else {
                    text = trimmed
                    font = UIFont.systemFont(ofSize: 10)
                }

                let attr: [NSAttributedString.Key: Any] = [.font: font, .foregroundColor: charcoalColor]
                let ns = NSAttributedString(string: text, attributes: attr)
                let h = ns.boundingRect(with: CGSize(width: maxW, height: 1000), options: .usesLineFragmentOrigin, context: nil).height
                ns.draw(in: CGRect(x: margin + (isBullet ? 8 : 0), y: y, width: maxW, height: h + 4))
                y += h + 4
            }
            y += 12
        }

        // Symptoms section
        if (reportType.id == "timeline" || reportType.id == "full" || content == nil) && !symptoms.isEmpty {
            if y > pageRect.height - 80 { ctx.beginPage(); y = margin }
            drawSectionHeader("Symptom Timeline", y: y, margin: margin, maxW: maxW, color: charcoalColor)
            y += 24

            let headerAttr: [NSAttributedString.Key: Any] = [.font: UIFont.systemFont(ofSize: 9, weight: .bold), .foregroundColor: UIColor.white]
            UIColor(red: 0.659, green: 0.212, blue: 0.345, alpha: 1).setFill()
            UIBezierPath(roundedRect: CGRect(x: margin, y: y, width: maxW, height: 20), cornerRadius: 3).fill()
            NSAttributedString(string: "Symptom", attributes: headerAttr).draw(at: CGPoint(x: margin + 8, y: y + 5))
            NSAttributedString(string: "Category", attributes: headerAttr).draw(at: CGPoint(x: margin + 180, y: y + 5))
            NSAttributedString(string: "Count", attributes: headerAttr).draw(at: CGPoint(x: margin + 320, y: y + 5))
            NSAttributedString(string: "Avg Sev", attributes: headerAttr).draw(at: CGPoint(x: margin + 380, y: y + 5))
            y += 22

            for (i, s) in symptoms.prefix(40).enumerated() {
                if y > pageRect.height - 60 { ctx.beginPage(); y = margin }
                if i % 2 == 1 {
                    UIColor(red: 0.973, green: 0.965, blue: 0.957, alpha: 1).setFill()
                    UIBezierPath(rect: CGRect(x: margin, y: y, width: maxW, height: 18)).fill()
                }
                let rowAttr: [NSAttributedString.Key: Any] = [.font: UIFont.systemFont(ofSize: 9), .foregroundColor: charcoalColor]
                NSAttributedString(string: s.symptom, attributes: rowAttr).draw(at: CGPoint(x: margin + 8, y: y + 4))
                NSAttributedString(string: s.category, attributes: rowAttr).draw(at: CGPoint(x: margin + 180, y: y + 4))
                let sevStr = s.severity.map { "\($0)/10" } ?? "—"
                NSAttributedString(string: sevStr, attributes: rowAttr).draw(at: CGPoint(x: margin + 380, y: y + 4))
                y += 18
            }
            y += 12
        }
    }

    private func drawSectionHeader(_ title: String, y: CGFloat, margin: CGFloat, maxW: CGFloat, color: UIColor) {
        let attr: [NSAttributedString.Key: Any] = [.font: UIFont.systemFont(ofSize: 14, weight: .semibold), .foregroundColor: color]
        NSAttributedString(string: title, attributes: attr).draw(at: CGPoint(x: margin, y: y))
        UIColor(red: 0.682, green: 0.643, blue: 0.604, alpha: 1).setFill()
        UIBezierPath(rect: CGRect(x: margin, y: y + 20, width: maxW, height: 0.75)).fill()
    }
}
